Notebooks: [Numpy](Numpy.ipynb) || [Numpy_Practico](Numpy_Practico.ipynb)

# S02 T04: Pràctica amb programació numèrica

##### Familiaritza't amb la Programació Numèrica a través de la llibreria NumPy. [NumPy](https://numpy.org/doc/stable/reference/index.html)

## Nivell 1

### * Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import numpy as np
import random

random_list=[]
for i in range(25):
    random_list.append(random.randint(10,99))
print("La Llista generada és:\n", random_list)

La Llista generada és:
 [82, 86, 44, 15, 94, 61, 50, 85, 39, 62, 25, 62, 59, 38, 96, 20, 10, 34, 38, 83, 50, 48, 27, 35, 14]


In [2]:
random_list_1D=np.array(random_list)        #Sense posar-li '.reshape(25,)', per defecte converteix la Llista 
print("Convertim la Llista en NParray:\n",random_list_1D)                                        # en Array 1D.

Convertim la Llista en NParray:
 [82 86 44 15 94 61 50 85 39 62 25 62 59 38 96 20 10 34 38 83 50 48 27 35
 14]


### * Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

###### a) _La funció creada genera el quadrat del número i l'imprimeix des de la funció sense retornar cap valor._

In [11]:
from matplotlib import pyplot as plt             
import random
import numpy as np

def toggle_cell_code(button_id):
    """
    Adds a button to toggle (show/hide) the code cell but not the output. 
    
    Parameters
    ----------
    button_id : str
        An identifier for cells that will hide/show when button is pressed.
    """
    
    from IPython.display import display_html
    my_html = '''
    <button type="button" id="%s" onclick="code_toggle('%s')">Oculta/Mostra Codi</button>
    <script>
    function code_toggle(my_id) {
        // get the parent element for the cell code and output
        var p = $("#"+my_id);
        if (p.length==0) return;
        while (!p.hasClass("cell")) {
            p = p.parent();
            if (p.prop("tagName") =="body") return;
        }
    // get the cell code and toggle its value
    var cell_code = p.find(".input");
    cell_code.toggle();
    }
    </script>
    ''' %(button_id, button_id)
    return display_html(my_html, raw=True)
    
toggle_cell_code("un_string_unico_y_reconocible")

###########################################################################################
###############  Aquí comença el codi del programa ########################################
###########################################################################################

random_list=[]                                               #Declarem la Llista buida amb "[ ]"
quadrat=int(input("Introdueix un número de l'1 al 10 : "))
print()

def quadrat_NxN(quadrat):
    for i in range(quadrat*quadrat):
        random_list.insert(i,random.randint(10,99))
    random_array=np.array(random_list)

    for i in range(0,quadrat*quadrat,quadrat):
        for j in range(quadrat):
            print(random_array[j+i], end=" ")
        print("")

    # Cridem a la funció passant-li el valor introduït per l'usuari, generem l'array i imprimim el resultat.
print("El quadrat quedaria així :\n")
quadrat_NxN(quadrat) 

Oculta/Mostra Codi

Introdueix un número de l'1 al 10 : 5

El quadrat quedaria així :

77 48 93 40 86 
15 95 72 39 21 
93 70 95 26 90 
10 70 52 69 97 
65 70 68 79 80 


###### b) _La funció creada genera el quadrat del número, el guarda a una variable i el retorna per imprimir-lo fora de la funció._

In [4]:
def quadrat_NxN(quadrat):
    random_list=[]                                               #Declarem la Llista buida amb "[ ]"
    resultat=''
    
    for i in range(quadrat*quadrat):
        random_list.insert(i,random.randint(10,99))

    random_array=np.array(random_list)

    for i in range(0,quadrat*quadrat,quadrat):
        for j in range(quadrat):
            resultat+=str(random_array[j+i])+' '
        resultat+="\n "
    return resultat

quadrat=int(input("Introdueix un número de l'1 al 10 : "))

   # Cridem a la funció passant-li el valor introduït per l'usuari, generem l'array i retornem el valor per ...
resultat=quadrat_NxN(quadrat)  
print(f"\nEl quadrat quedaria així : \n\n {resultat}")             # ... imprimir el resultat.

Introdueix un número de l'1 al 10 : 5

El quadrat quedaria així : 

 98 12 39 14 82 
 77 37 75 86 58 
 22 16 29 98 31 
 89 74 83 28 20 
 59 31 95 81 86 
 


### * Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [12]:
def calcula_totals(elements_fila, elements_columna, elements_totals):
    random_list=[]
    for i in range(elements_totals):
        random_list.append(random.randint(10,99))
    random_list_2D=np.array(random_list).reshape(elements_fila,elements_columna)
    print(f"Creem l'Array 2D amb els valors introduïts:\n {random_list_2D} del tipus: {random_list_2D.dtype} \n")
    print("Sumant Files i Columnes...\n")
    for i in range(len(random_list_2D)):
        print(f"Suma Fila {i}:", np.sum(random_list_2D[i]))
    print()
    for i in range(len(random_list_2D)):
        print(f"Suma Columna {i}:", np.sum(random_list_2D[:,i]))
    print("\nSuma de tots els elements: ", np.sum(random_list_2D))
    
elements_fila=int(input("Crearem una Matriu 2D. Quants elements vols per Fila? : "))
elements_columna=int(input("                    Quants elements vols per Columna? : "))
elements_totals=elements_fila * elements_columna
print("Els totals :")
calcula_totals(elements_fila, elements_columna, elements_totals)

Crearem una Matriu 2D. Quants elements vols per Fila? : 5
                    Quants elements vols per Columna? : 5
Els totals :
Creem l'Array 2D amb els valors introduïts:
 [[30 35 88 82 42]
 [53 16 55 76 84]
 [62 28 77 12 17]
 [75 52 83 89 91]
 [59 81 61 74 79]] del tipus: int32 

Sumant Files i Columnes...

Suma Fila 0: 277
Suma Fila 1: 284
Suma Fila 2: 196
Suma Fila 3: 390
Suma Fila 4: 354

Suma Columna 0: 279
Suma Columna 1: 212
Suma Columna 2: 364
Suma Columna 3: 333
Suma Columna 4: 313

Suma de tots els elements:  1501


### * Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

>Los coeficientes de correlación lineal son estadísticos que cuantifican la asociación lineal entre dos variables numéricas. Existen diferentes tipos, de entre los que destacan el __Pearson__, __Rho de Spearman__ y __Tau de Kendall__.

#### Tutorial de la matrix de correlacion de Python !!!!!!!!!!!!!!!!! 

[LikeGeeks - Tutorial de la matrix de correlacion de Python](https://likegeeks.com/es/matrix-correlacion-python/)

#### Función Pandas DataFrame.corr():

[DelfStack](https://www.delftstack.com/es/api/python-pandas/pandas-dataframe-dataframe.corr-function/)

#### Cómo calcular la correlación en Python:

[cienciadedatos.net - Correlación lineal con Python !!!!!!!!!!!!!!!!!!!!!!!!!!](https://www.cienciadedatos.net/documentos/pystats05-correlacion-lineal-python.html)<br>
[statologos - Cómo calcular la correlación en Python](https://statologos.jaol.net/correlacion-en-python/)<br>
[statologos - Coeficiente de correlación de Pearson](https://statologos.jaol.net/coeficiente-de-correlacion-de-pearson/)<br>
[statologos - Coef. de correlación de rango de Spearman](https://statologos.jaol.net/python-de-correlacion-de-spearman/)<br>
[statologos - Tau de Kendall: definición + ejemplo](https://statologos.jaol.net/kendalls-tau/)
[statologos - Correlaciones Stata](https://statologos.jaol.net/correlaciones-stata/)

#### Comparación de los coeficientes de Pearson y Spearman:

[MiniTab 18](https://support.minitab.com/es-mx/minitab/18/help-and-how-to/statistics/basic-statistics/supporting-topics/correlation-and-covariance/a-comparison-of-the-pearson-and-spearman-correlation-methods/)

-------------

### [Continuació a ... S02T04_Correlations](#S02T04_Correlations.ipynb)